### ISSUE TITLE
Question - a lot of metrics with the same name but different "hostname"

### ISSUE THREAD

**Issue by allburov** [danihodovic/celery-exporter#116]
Hi! Thank you for creating and supporting such a helpful project!

I have a question - we use `celery==5.2.6` and the latest `celery-exporter` (docker) and using Grafana Cloud (free version)
After a week I see that ran out of free tier on Grafana and we have more then 10 000 metrics for celery!

What happened:
There're a lot of metric with `hostname=gen1234@myhostname` and only one with `celery@myhostname`
```
celery_task_received_total{hostname="gen516136@myhostname",name="app.tasks.send_email"} 0.0
celery_task_received_total{hostname="gen516136@myhostname",name="app.tasks.send_email"} 0.0
celery_task_received_total{hostname="celery@myhostname",name="app.tasks.send_email"} 0.0
```

Look like `gen1234` metrics are created for each thread in worker and after restart of celery worker daemon celery-exporter keep sending these metrics to prometheus even if they don't have new data. Restaring help here, so I just configured CD process and we restart celery-exporter's docker after celery workers.

The question is - is there a way to filter out them from the metrics and what is their purpose?

**Comment by allburov** [comment]
Oh, I see, `gen123` probably django instances who send tasks.
`celery_task_received_total` is increased in `celery@hostname` metric and `celery_task_sent_total` is increased in `gen123` metric

**Comment by danihodovic** [comment]
See https://github.com/danihodovic/celery-exporter/pull/72

**Comment by allburov** [comment]
@danihodovic thank you for the help!
I'll look at this closely
