### ISSUE TITLE
No tests for `celery_task_sent` metric in test_integration

### ISSUE THREAD

**Issue by allburov** [danihodovic/celery-exporter#121]
I didn't find tests for `celery_task_sent` in [tests_cli.py:test_integration](https://github.com/danihodovic/celery-exporter/blob/master/src/test_cli.py)
I tried to add it, but the metric always give me `0.0` value!

It looks like celery doesn't send `task-sent` in tests, even tho there's `"task_send_sent_event": True,` in [conftest.py](https://github.com/danihodovic/celery-exporter/blob/master/conftest.py)

@danihodovic don't you remember - why there's no test for `celery_task_sent`? 
May be you already investigated the problem, it'd be good to add test there

**Comment by danihodovic** [comment]
You have a good eye for detail. I've now noticed that the metric is only sent in my production environment if task_send_sent_event is enabled: https://docs.celeryq.dev/en/stable/userguide/configuration.html#std-setting-task_send_sent_event

```
celery_task_sent_total{hostname="gen12@django-wtf-worker-0",name="django_apps.core.github_tasks.index_contributors"} 2.0
celery_task_sent_total{hostname="gen12@django-wtf-worker-0",name="django_apps.core.github_tasks.index_repositories_by_keyword"} 1.0
celery_task_sent_total{hostname="gen12@django-wtf-worker-0",name="django_apps.core.github_tasks.index_followers"} 1.0
celery_task_sent_total{hostname="gen12@django-wtf-worker-0",name="django_apps.core.pypi_tasks.index_pypi_projects"} 1.0
```
