### ISSUE TITLE
celery_worker_up reporting 1 for turned off workers

### ISSUE THREAD

**Issue by janjaros** [danihodovic/celery-exporter#137]
Hi, 
has anyone noticed when scaling up/down the celery workers (pods) that the metric celery_worker_up just keeps rising and reports all previous workers as running? 
When I try to run `celery -A proj inspect stats` it returns the correct amount of workers. 
Looking at the code I dont see anything weird.

Thanks a lot for help

**Comment by danihodovic** [comment]
I haven't scaled workers up or down, but it may be related to this https://github.com/danihodovic/celery-exporter/pull/120

If you can think of a solution fork the project, build a docker image and try it out. If it works submit a pull-request.

**Comment by janjaros** [comment]
I will try to find time to set up a test env and find the issue :-)
