### ISSUE TITLE
Can't pass json-like string as --broker-transport-option

### ISSUE THREAD

**Issue by kittywaresz** [danihodovic/celery-exporter#142]
Hi!

I want to connect this exporter to Sentinel that uses Redis, in my case it means that I have to pass dict object to Celery app instance (https://github.com/danihodovic/celery-exporter/blob/master/src/exporter.py#L211), but currently it's impossible because of _--broker-transport-option_ params handling logic, it's restricted with key=value pattern and value will always by a string

What I'm trying to achieve:

`docker run -p 9808:9808 -it --rm danihodovic/celery-exporter --broker-url sentinel://:xxx@xx.xx.xx.xx:26379/1 --broker-transport-option master_name=master01 --broker-transport-option sentinel_kwargs="{\"password\": \"xxx\"}" --log-level DEBUG`

What I get (it happened because **self.sentinel_kwargs** value equals to **{"password": "xxx"}** string, but dict was expected by Redis client class):

```
  File "celery-exporter-playground/venv/lib/python3.9/site-packages/redis/sentinel.py", line 186, in <listcomp>
    Redis(hostname, port, **self.sentinel_kwargs)
TypeError: redis.client.Redis() argument after ** must be a mapping, not str
```

Is it possible to add parsing json-like strings in attempt to transform it to Python dict before updating transport_options object with this value? (As it implemented in https://github.com/OvalMoney/celery-exporter/blob/master/celery_exporter/__main__.py#L130?)

**Comment by danihodovic** [comment]
Open a PR and I'll take a look
