### ISSUE TITLE
Docker build latest tag not the latest release

### ISSUE THREAD

**Issue by cfarrend** [danihodovic/celery-exporter#158]
Hi all,

Noticed that the `latest` tag in [DockerHub](https://hub.docker.com/r/danihodovic/celery-exporter/tags) is 4 months old while the newest image `0.5.4` is 2 months old. Thought I'd bring this up in case this wasn't intentional.

![image](https://user-images.githubusercontent.com/12799795/191924941-67bdfb27-1443-4248-8898-b22270d00d36.png)

Thanks for this project!

**Comment by danihodovic** [comment]
Thanks for the reminder. I've pushed danihodovic/celery-exporter:latest.
