### ISSUE TITLE
celery-exporter does not work with SQS Broker

### ISSUE THREAD

**Issue by vipulvv** [danihodovic/celery-exporter#162]
I've noticed a PR for SQS support - https://github.com/danihodovic/celery-exporter/pull/1

Followed prerequisites, like enabling celery events with -E flag(enable_events), & ran the `celery-exporter --broker-url <SQS_Queue_URL> -l localhost:8888`

It starts with the following logs:
```
[2022-09-28 19:57:57,757] botocore.credentials:INFO: Found credentials from IAM Role: <IAM_ROLE>
[2022-09-28 19:57:57,907] kombu.mixins:INFO: Connected to sqs://<SQS_URL>//
```
I could see two queues were created with name:
```
  1. celeryev-<UUID>
  2. <UUID>-reply-celery-pidbox
```
However, I could not see the celery metrics. Currently, it shows the following on scraping url:
```
python_gc_objects_collected_total{generation="0"} 1742.0
python_gc_objects_collected_total{generation="1"} 4233.0
python_gc_objects_collected_total{generation="2"} 257.0
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
python_gc_collections_total{generation="0"} 233.0
python_gc_collections_total{generation="1"} 21.0
python_gc_collections_total{generation="2"} 1.0
python_info{implementation="CPython",major="3",minor="8",patchlevel="13",version="3.8.13"} 1.0
process_virtual_memory_bytes 5.22747904e+08
process_resident_memory_bytes 7.9413248e+07
process_start_time_seconds 1.66439535912e+09
process_cpu_seconds_total 1.53
process_open_fds 14.0
process_max_fds 1024.0
celery_workers{namespace="celery"} 0.0
```

I've also observed the following error, which I did not observe while testing `celery-prometheus-exporter`(it does not show metrics either).
```
[2022-09-28 19:58:12,470] workers-thread:ERROR: Error while pinging workers
```

**Questions:**
1. Is there any prerequisite that seems to be missed?
2. Is SQS supported & tested as broker for celery metrics?
3. Is there a way to work around this issue?

Let me know if you need any additional information.

**Comment by danihodovic** [comment]
You are our SQS pioneer.

I've tested it for Redis and RabbitMQ where it works. SQS is supported by Celery / Kombu, so theoretically we could make it work.

Feel free to change the source code as you see fit and submit a patch :D

**Comment by soumik-avoma** [comment]
@danihodovic Any update with the SQS broker support? 
I tried pulling the latest image from docker hub, tried running by `docker run -p 9808:9808 danihodovic/celery-exporter --broker-url=sqs://sqs.<region>.amazonaws.com/<account_id>/<queue_name>`
Got error at:
```
cli.py 5 <module>
cli(auto_envvar_prefix="CE")

core.py 1128 __call__
return self.main(*args, **kwargs)

core.py 1053 main
rv = self.invoke(ctx)

core.py 1395 invoke
return ctx.invoke(self.callback, **ctx.params)

core.py 754 invoke
return __callback(*args, **kwargs)

cli.py 68 cli
Exporter(formatted_buckets).run(ctx.params)

exporter.py 242 run
with self.app.connection() as connection:

base.py 851 connection
return self.connection_for_write(

base.py 816 connection_for_write
return self._connection(url or self.conf.broker_write_url, **kwargs)

base.py 867 _connection
return self.amqp.Connection(

connection.py 181 __init__
if not get_transport_cls(transport).can_parse_url:

__init__.py 85 get_transport_cls
_transport_cache[transport] = resolve_transport(transport)

__init__.py 70 resolve_transport
return symbol_by_name(transport)

imports.py 56 symbol_by_name
module = imp(module_name, package=package, **kwargs)

__init__.py 127 import_module
return _bootstrap._gcd_import(name[level:], package, level)

<frozen importlib._bootstrap> 1030 _gcd_import


<frozen importlib._bootstrap> 1007 _find_and_load


<frozen importlib._bootstrap> 986 _find_and_load_unlocked


<frozen importlib._bootstrap> 680 _load_unlocked


<frozen importlib._bootstrap_external> 790 exec_module


<frozen importlib._bootstrap> 228 _call_with_frames_removed


SQS.py 132 <module>
from botocore.client import Config

ModuleNotFoundError:
No module named 'botocore'
```

Also I couldnt't find the sqs.py file anywhere. 
It would be great if you could help.

**Comment by danihodovic** [comment]
If someone wants to give it a try to implement this we could use Localstack to emulate SQS in development. 

https://docs.localstack.cloud/user-guide/aws/sqs/

**Comment by danihodovic** [comment]
I tried to implement support for SQS, but I don't think it's currently possible. SQS does not emit Celery events and the exporter relies on events for monitoring.

https://docs.celeryq.dev/en/stable/getting-started/backends-and-brokers/sqs.html#caveats

> SQS doesn’t yet support events, and so cannot be used with celery events, celerymon, or the Django Admin monitor.
