### ISSUE TITLE
How to calculate “num of tasks to be execute”

### ISSUE THREAD

**Issue by Liubey** [danihodovic/celery-exporter#175]
Hi,
If I want to calculate the num of tasks which need to be execute in the future, May I use 
`celery_task_sent - celery_task_received`?

**Comment by Liubey** [comment]
Cause these counters got zero with code:
`counter.labels(**_labels).inc(0)`
via by https://github.com/danihodovic/celery-exporter/issues/47

“celery_task_sent - celery_task_received” will got negative,It is violate common sense？

such as changed with timeline:

task-send counter: 1 1 0 1 0
task-recv-counter: 0 1 2 2 3
at the last, when “celery_task_sent - celery_task_received”,got -3.
Is it right?

**Comment by adinhodovic** [comment]
Yes sound about right. Or u can do it by queue `celery_queue_length` if you do not need task granularity.
