### ISSUE TITLE
celery_queue_length is not getting values always zero

### ISSUE THREAD

**Issue by ahelmy** [danihodovic/celery-exporter#190]
Thank you for this project.
We are using it in our company, however this metric not working celery_queue_length always have zero.
We are using redis.

**Comment by ahelmy** [comment]
@danihodovic your help please :)

**Comment by danihodovic** [comment]
Hi Ali. The queue length is working at my job. You will have to provide more information if we are going to debug this together.

**Comment by ahelmy** [comment]
I am using docker version 0.5.3. Do you think if used last version would matter?

**Comment by danihodovic** [comment]
The queue length only works for RabbitMQ. Are you using RabbitMQ?

**Comment by ahelmy** [comment]
No using redis. No way to make it work? Or a way to ge the value

**Comment by ahelmy** [comment]
If no way please check this PR updating documentation 
https://github.com/danihodovic/celery-exporter/pull/191

**Comment by ahelmy** [comment]
Can you share celery configuration in python project, for example are you override default name of queue ?

**Comment by ahelmy** [comment]
and is the default one showed in the queue_length metric ?

**Comment by ahelmy** [comment]
I figured out the problem and created PR
