### ISSUE TITLE
No queue, no events

### ISSUE THREAD

**Issue by andreynovikov** [danihodovic/celery-exporter#193]
I'm using Django + Celery + Redis + django-celery-results on a single host. Everything works like a charm. I'm trying to run celery-exporter (from cli, git cloned source master branch, tried 0.4.1 as well) and get the following:
* `worker-heartbeat` event is successfully received
* `task-sent` event for all initiated tasks is successfully received
* no other task events are received
* `track_queue_length` shows `Queue 'celery' not found` error in debug log

`LLEN celery` in `redis-cli` shows that queue. Celery versions are equal in Django and celery-exporter: 5.2.3. Have no idea where to look further.

**Comment by danihodovic** [comment]
celery_queue_length only works for RabbitMQ https://github.com/danihodovic/celery-exporter/issues/190

As for the other metrics - do you have a worker running?

**Comment by andreynovikov** [comment]
Yes, worker is running, tasks are executed. Also in Django I have subscriptions for [corresponding signals](https://docs.celeryq.dev/en/stable/userguide/signals.html) and they work well:

```
from celery.signals import task_received

@task_received.connect
def on_task_received(request, **kwargs):
   ...
```

**Comment by andreynovikov** [comment]
I've found the problem: for some reason celery didn't process `CELERY_SEND_EVENTS`. I have added direct setting to celery worker and it started sending all events.

**Comment by andreynovikov** [comment]
Any chance to merge https://github.com/danihodovic/celery-exporter/pull/192 ?

**Comment by danihodovic** [comment]
> Any chance to merge #192 ?

I will hopefully have time to look at it before the end of the year.
