### ISSUE TITLE
Queue filter doesn't seem to be working

### ISSUE THREAD

**Issue by michaelschem** [danihodovic/celery-exporter#198]
When I filter by queue name, the drop down shows all of my queue names, but when I select any of them, it shows no data.

<img width="332" alt="image" src="https://user-images.githubusercontent.com/2836129/210119933-878bc19f-2de7-4a8d-9114-6b80438cb4d3.png">

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/2836129/210119940-f2e71e10-d528-44ca-8000-323a9c2e5281.png">

**Comment by ahelmy** [comment]
Hi, could you share prometheus results ?

**Comment by michaelschem** [comment]
@ahelmy here are some exporter logs 
[metrics.txt](https://github.com/danihodovic/celery-exporter/files/10374744/metrics.txt)

**Comment by michaelschem** [comment]
@danihodovic I'm using RabbitMQ so this shouldn't be a problem.

**Comment by michaelschem** [comment]
@ahelmy sorry, not sure what grafana output you're expecting, does this screenshot help, or are you looking for logs of some sort?
![image](https://user-images.githubusercontent.com/2836129/211372562-7cdeff3d-198e-4377-a433-0edfd7bbfdfa.png)

[This](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) is the chart I'm using.

**Comment by michaelschem** [comment]
Found a workaround. Since the queue is in the name, I can use the approximate equal operator (~=) with the queue name and the an asterisk. Ex (name != gov.*) for all queues in gov queue.
![image](https://user-images.githubusercontent.com/2836129/211461995-2ebc3747-5864-4530-b69c-ce20b99df2fc.png)

**Comment by danihodovic** [comment]
Cc @adinhodovic grafana meister

**Comment by adinhodovic** [comment]
I dont know native grafana filters which are in the picture and I would not recommend that approach either way. But to this issue - the latest exporter has all task metrics labeled with queue and the latest 2 dashboards has filters for the queue and a queue length graph.

Note: This also means that all data before the upgrade has no queue labels so filters wont work for those (they will be filtered out)

https://grafana.com/grafana/dashboards/17508-celery-tasks-by-task/
https://grafana.com/grafana/dashboards/17509-celery-tasks-overview/

**Comment by michaelschem** [comment]
Wow, this is an awesome update.  Love the queue length feature.

Unfortunately, the queue name filter still isn't populating.  I do have queue lengths showing up which is interesting.

![image](https://user-images.githubusercontent.com/2836129/214727573-c305ed39-b5d7-4add-984c-3eed6efa6adc.png)

Also, although I only just updated my grafana views, the celery exporter is on version `0.7.1` for about 32 hours now.

```shell
root@celery-exporter-78d7556944-tnrcn:/app# cat pyproject.toml  | grep version
version = "0.7.1"
```

**Comment by adinhodovic** [comment]
> Wow, this is an awesome update. Love the queue length feature.
> 
> Unfortunately, the queue name filter still isn't populating. I do have queue lengths showing up which is interesting.
> 
> ![image](https://user-images.githubusercontent.com/2836129/214727573-c305ed39-b5d7-4add-984c-3eed6efa6adc.png)
> 
> Also, although I only just updated my grafana views, the celery exporter is on version `0.7.1` for about 32 hours now.
> 
> ```shell
> root@celery-exporter-78d7556944-tnrcn:/app# cat pyproject.toml  | grep version
> version = "0.7.1"
> ```

0.7.1 has a bug pls 0.7.2

**Comment by adinhodovic** [comment]
And let me know in 2-3 when metrics are aligned with the correct labels (only correct in 0.7.2) if filters are working and so on.

**Comment by michaelschem** [comment]
very nice!

Looks like you've got latest tagged as 0.7.1 btw

![image](https://user-images.githubusercontent.com/2836129/214733187-7a171014-59aa-49cc-8182-2650e1c64785.png)

**Comment by michaelschem** [comment]
Oh, and I can confirm this works by setting my time to the last 15 min, so I guess I'll close.  Thanks for the fix! 🍻 

![image](https://user-images.githubusercontent.com/2836129/214733719-ccde8ff7-4e09-4258-a54a-899b5a805cd7.png)

**Comment by michaelschem** [comment]
Oh, and I can confirm this works by setting my time to the last 15 min, so I guess I'll close.  Thanks for the fix! 🍻 

![image](https://user-images.githubusercontent.com/2836129/214733719-ccde8ff7-4e09-4258-a54a-899b5a805cd7.png)

**Comment by adinhodovic** [comment]
@michaelschem glad to hear that michael :) Let me know if u have any other proposed dashboard changes!

Also, created recently https://github.com/adinhodovic/django-mixin with dashboards and alerts for the django-prometheus project. If u use that as well let me know with some feedback :)

**Comment by michaelschem** [comment]
Oh, man I'm definitely gonna try that one out. This would be so helpful for us!
