### ISSUE TITLE
Add helm repository

### ISSUE THREAD

**Issue by gciria** [danihodovic/celery-exporter#236]
How are you adding the helm repository?
I see `index.html` in the `gh-pages` branch. But it does not work. 

```
$ helm repo add celery-exporter https://github.com/danihodovic/celery-exporter

Error: looks like "https://github.com/danihodovic/celery-exporter" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/danihodovic/celery-exporter/index.yaml : 404 Not Found
```

**Comment by gciria** [comment]
You probably need to add the `tar.gz` in the branch `gh-pages`.

**Comment by adinhodovic** [comment]
Repo: https://danihodovic.github.io/celery-exporter
Version: 0.6.2

Works fine for me.

**Comment by gciria** [comment]
Oh ok.. I was using the wrong link. Everything working fine. Thanks for the quick response. :)
