### ISSUE TITLE
Memory usage grows non-stop

### ISSUE THREAD

**Issue by humbertowoody** [danihodovic/celery-exporter#253]
Hello!

First of all, thank you for this amazing project.

We're seeing the memory usage for the container with the exporter growing non-stop over time. It grows until an `OOM` error arises and Kubernetes restarts the container. 

This is a look at the memory usage over 7 days:

<img width="1329" alt="Screenshot 2023-06-02 at 11 24 36" src="https://github.com/danihodovic/celery-exporter/assets/8785685/f4c48069-0e8b-4f21-86ee-95724994dd47">

I'm unsure if this is related, but our current Prometheus configuration is as follows:

- 10s scrape interval.
- 10s timeout.

I'll share with you how our  Grafana dashboard metrics for the said week:

<img width="1436" alt="Screenshot 2023-06-02 at 11 26 17" src="https://github.com/danihodovic/celery-exporter/assets/8785685/2a7ea2ec-a6b1-4862-80f6-71462c1fa681">

Due to https://github.com/danihodovic/celery-exporter/issues/157 we switched from a Deployment to a StatefulSet, and it improved greatly our Prometheus queries latency, however, I worry about OOM errors, but I'm unsure what configuration may be the cause of it.

Thanks in advance! 

Edit: Just for clarification, we're using the official Docker image without any modifications, the only parameter is the Redis Broker Queue URL.

**Comment by humbertowoody** [comment]
We updated to the latest version (0.9.0) and the issue seems to be fixed! Thanks! :)

**Comment by danihodovic** [comment]
Thank you to @adinhodovic
