### ISSUE TITLE
Grafana dashboard "Celery Overview" is a duplicate of dashboard "Celery task by task" since update of 2023-06-27

### ISSUE THREAD

**Issue by ianbabysre** [danihodovic/celery-exporter#258]
Hi

Since the last update (Last update: 2023-06-27T13:49:19), both dashboard are the same :

https://grafana.com/grafana/dashboards/17509-celery-tasks-by-task/
https://grafana.com/grafana/dashboards/17508-celery-tasks-by-task/

Somehow the Celery overview got overwritten

**Comment by danihodovic** [comment]
@adinhodovic grafana dashboard expert pls

**Comment by ianbabysre** [comment]
I'm closing this issue as the dashboard is back !

Thank you
