### ISSUE TITLE
PYPI support

### ISSUE THREAD

**Issue by Niccolum** [danihodovic/celery-exporter#265]
Hello!

Please, add this library to PYPI

**Comment by danihodovic** [comment]
Hello Nikolai,

Please, feel free to open a pull-request.

**Comment by danihodovic** [comment]
https://pypi.org/project/prometheus-exporter-celery/

**Comment by WilliamDEdwards** [comment]
Hi @danihodovic,

Would you consider adding that PyPI URL to the README? I was also looking for a `pip install` method, and having it in the README implies it's 1) official and 2) supported :)

**Comment by danihodovic** [comment]
Open a pull-request and we can do it

**Comment by WilliamDEdwards** [comment]
> Open a pull-request and we can do it

https://github.com/danihodovic/celery-exporter/pull/366
