### ISSUE TITLE
May I use  Flask = 2.3.2 on the celery-exporter?

### ISSUE THREAD

**Issue by 787627858** [danihodovic/celery-exporter#285]
<img width="855" alt="image" src="https://github.com/danihodovic/celery-exporter/assets/46810394/37b80c20-52bb-4266-af1c-39b513934000">

**Comment by danihodovic** [comment]
Open a pull-request

**Comment by danihodovic** [comment]
Resolved in v0.10.2 and https://github.com/danihodovic/celery-exporter/pull/291
