### ISSUE TITLE
Update dashboards on Grafana library

### ISSUE THREAD

**Issue by cjaca** [danihodovic/celery-exporter#330]
Hi @danihodovic, @adinhodovic 

Could you please update the Grafana library with the latest versions of the following dashboards?

1. [Celery Tasks Overview](https://grafana.com/grafana/dashboards/17509-celery-tasks-overview/)  with https://github.com/danihodovic/celery-exporter/blob/master/celery-mixin/dashboards_out/celery-tasks-overview.json 
2. [Celery Tasks by Task](https://grafana.com/grafana/dashboards/17508-celery-tasks-by-task/) with https://github.com/danihodovic/celery-exporter/blob/master/celery-mixin/dashboards_out/celery-tasks-by-task.json

The current versions are no longer supported due to the lack of Angular support in the new Grafana version.

I believe this update is essential, as it could attract more contributors to the project (including myself! 😊).

**Comment by danihodovic** [comment]
I would like to do this, but I don't think the dashboards are good enough for my own use case. I'm working on revamping them after not having touched them for over a year.

In the meantime you can generate them yourself: https://github.com/danihodovic/celery-exporter/tree/master/celery-mixin#generate-config-files

**Comment by adinhodovic** [comment]
These two run the latest grafonnet version:

- https://grafana.com/grafana/dashboards/17508-celery-tasks-by-task/
- https://grafana.com/grafana/dashboards/17509-celery-tasks-overview/

There are also the newest set of generated dashboards at https://github.com/danihodovic/celery-exporter/tree/master/celery-mixin/dashboards_out

**Comment by cjaca** [comment]
Thanks @adinhodovic !
I will also try generating dedicated ones with jsonnet.
