### ISSUE TITLE
Suggestion: add README for setting "celery-exporter" as datasource

### ISSUE THREAD

**Issue by nickatnight** [danihodovic/celery-exporter#34]
As the title suggests, it would be nice if there was a README on how to add this exporter as a datasource in Grafana.

For me, I'm having trouble have get my local Grafana instance to find the exporters http server. I'm using compose to bring up my containers, but I still keep getting 404 when adding a new datasource (`http://celery-exporter:9808/metrics`). Im able to see my tasks at `localhost:9808/metrics`, as well as `curl` the metrics endpoint from a container on the network. It's quite strange

Edit:

Figured it out. Your Flask server does not expose `api/v1/query`, which Grafana relies on to query metrics

<img width="514" alt="Screen Shot 2021-04-02 at 3 40 33 PM" src="https://user-images.githubusercontent.com/8783431/113459325-fdc22200-93c9-11eb-816d-39f927d6dcb6.png">

Edit 2:

Adding image from container `curl`
<img width="896" alt="Screen Shot 2021-04-02 at 3 57 48 PM" src="https://user-images.githubusercontent.com/8783431/113460053-48dd3480-93cc-11eb-8ef8-9e260d8b8745.png">

**Comment by danihodovic** [comment]
Are you sure your setup is correct? This exporter exposes metrics to Prometheus. Grafana is used to query Prometheus, so your datasource should be Prometheus, not the exporter.

celery-exporter => Prometheus => Grafana

**Comment by nickatnight** [comment]
@danihodovic Ah ok my prom settings were botched. Figured it out thanks 👍
