### ISSUE TITLE
Missing metrics in prometheus.

### ISSUE THREAD

**Issue by surister** [danihodovic/celery-exporter#47]
Hi, I am missing 'fail' metrics such as 
![image](https://user-images.githubusercontent.com/37985796/121885241-39eff800-cd14-11eb-8b74-bc895e3e2667.png)

Every metric that has to be with failures I don't get, the others work fine.

I am using the latest version of prometheus, grafana and celery-exporter.

My celery start script:
```sh
celery -A tasks worker -l INFO -E -c 10 -n worker1@%h
```

Celery dockerfile
```Dockerfile
FROM python:3.8.6

RUN useradd -ms /bin/bash celery
WORKDIR /home/kektop
USER celery

COPY celery/* ./

RUN pip install -r requirements.txt
ENV PATH="${PATH}:/home/celery/.local/bin"

#CMD ["tail", "-f", "/dev/null"]
CMD ["bash", "celery_start.sh"]
```

celeryconfig.py
```python
broker_url = 'amqp://guest:guest@localhost:5672//'

imports = ('tasks',)
worker_send_task_events = True
task_send_sent_event = True
```

**Comment by danihodovic** [comment]
Do you have any failing tasks?

**Comment by surister** [comment]
I do not, shouldn't it report 0?

**Comment by danihodovic** [comment]
I honestly don't know. We initiate the counter when the process starts, but I don't know if the Prometheus registry returns a 0 or no metrics at all if the counter has never been incremented.

**Comment by surister** [comment]
I purposely made a few tasks fail and now I get the desired metric, I'd assume it would report 0.
Otherwise grafana tables will throw no data.

**Comment by danihodovic** [comment]
If there is a way to instantiate the counters with 0 feel free to open a PR. It hasn't been an issue for me because we always have failing tasks.

**Comment by danihodovic** [comment]
Thank @hiaselhans for resolving this one.
