### ISSUE TITLE
celery_task_rejected and celery_task_failed metrics are not updating even if the celery task is failing

### ISSUE THREAD

**Issue by kanhaiya787** [danihodovic/celery-exporter#48]
I have intergerate this celery exporter in my django app and set these two fields as True in settings:
CELERY_WORKER_SEND_TASK_EVENTS = True
CELERY_TASK_SEND_SENT_EVENT = True

The celery_task_failed metric is not getting update even after my celery task is failing to execute and throwing an exception. I have use the docker image and passed my broker url. I have attached my yaml file for deployment and the metric data which shows only some data and not the failed task data. 

[Metric.txt](https://github.com/danihodovic/celery-exporter/files/6672119/Metric.txt)

[celery-exporter.txt](https://github.com/danihodovic/celery-exporter/files/6672143/celery-exporter.txt)

**Comment by kanhaiya787** [comment]
It was working fine the before day where it was throwing the exception and setting celery_task_failed metric but now its doesnt update it, the code is same but now its not showing me that failed task in metrics.

**Comment by danihodovic** [comment]
I have no problems with those two metrics. If you think you've found a bug a pull-request is welcome.

**Comment by kanhaiya787** [comment]
Hi, actually the issue was from my end I didn't enable or use to the -E options in my celery command to send task related data.
Thanks for your quick reply, I wanted to know if we are going to get the metric for getting the size of queue, it would be really helpful if we can have that metric data as well.

**Comment by danihodovic** [comment]
No worries :+1: I'm happy that this project is in use.

If you'd like to add the metric for the queue size please open a PR. AFAIK Celery does not expose this through their metrics interface.
