### ISSUE TITLE
support transport options

### ISSUE THREAD

**Issue by pkoszalkaa** [danihodovic/celery-exporter#54]
Hi,

It would be great if  transport_options param would be added here. So in case where broker is redis-sentinel i could pass master name.

Cheers.

**Comment by danihodovic** [comment]
Would you consider opening a PR? Transport options is a dict of values known to me (https://docs.celeryproject.org/en/stable/userguide/configuration.html#std-setting-broker_transport_options), how would your configuration for sentinel look like? Can it be passed in as cli options?

**Comment by pkoszalkaa** [comment]
It could be a CLI option, so for example starting exporter would look like

celery-exporter --broker-url=sentinel://redis-sentinel/1' --transport-options={"master_name": "my-master-name"}
