### ISSUE TITLE
Add option to set log-level

### ISSUE THREAD

**Issue by brandon-dp** [danihodovic/celery-exporter#67]
Thanks @danihodovic for picking up the torch and making this exporter 🙌 

I noticed the default log-level for the Docker version of the exporter is set to `DEBUG`. This can create quite a lot of noise in production envs where we might not need that level of verbosity.

Could you add a CLI option to allow users to specify the log-level?

**Comment by danihodovic** [comment]
I can have a look at this next week. If you're willing to make a PR I'll also have a look at that :handball_person:

**Comment by danihodovic** [comment]
Fixed in #77
